spring:
  datasource:
    url: jdbc:mariadb://jamjam.hopto.org/dev?autoReconnect=true
    username: ${db.id}
    password: ${db.pw}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
   properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true